import React from 'react';
import {api,imageURL} from './api';
const names={queued:'待機中',sending:'送信中・生成中',completed:'完了',failed:'失敗',unknown:'API結果不明',local_error:'ローカル処理失敗（応答回収可）',cancelled:'待機取消'};
export default function History({jobs,onLoad,onResult,onEdit,onCancel,onReprocess,onGPULoad,gpuJobs=[],onGPURefresh,embedded=false}){
 const merged=[...jobs,...gpuJobs].sort((a,b)=>Date.parse(b.created)-Date.parse(a.created));
 return <section className={embedded?'history-content':'history'}>{embedded?null:<h2>履歴・ジョブ <small>{merged.length}件</small></h2>}
 {merged.length===0?<div className="empty">まだ履歴がありません<span>画像を編集して、ここに履歴が表示されます</span></div>:
 <div className="table-scroll"><table><thead><tr><th>日時・状態</th><th>指示文・処理</th><th>モデル・寸法</th><th>結果・操作</th></tr></thead>
 <tbody>{merged.map(j=>j.kind==='local_gpu'?<tr key={'gpu:'+j.id}><td>{new Date(j.created).toLocaleString('ja-JP')}<strong className="status">{({queued:'待機',loading:'モデル読込',upscaling:'拡大処理',adjusting:'サイズ調整',saving:'保存',completed:'完了',failed:'失敗',cancelled:'取消',cancel_requested:'取消要求中',interrupted:'中断',export_failed:'保存失敗'})[j.status]} · ローカルGPU</strong><small>{j.elapsed??0}秒</small></td><td>{j.params.kind==='diagnostic'?'GPU環境診断':'アップスケール'}<small>{j.message}</small>{j.total?<small>{j.done}/{j.total} タイル</small>:null}</td><td>SwinIR / FP32<small>{j.params.options?.width} × {j.params.options?.height}</small><small>API料金なし</small></td><td>{j.output?<div className="result-thumbs"><div className="history-output"><button onClick={()=>onResult(j.output)} aria-label="SwinIR結果を拡大表示"><img src={imageURL(j.output.id)} alt="SwinIR結果"/></button><button onClick={()=>onEdit({params:j.params.context||{}},j.output)}>次の編集対象にする</button><a href={'/api/assets/'+j.output.id+'/download'} download>PNGダウンロード</a></div></div>:null}{['queued','loading','upscaling','adjusting','saving'].includes(j.status)?<button onClick={async()=>{try{await api('upscale/jobs/'+j.id+'/cancel',{});await onGPURefresh();}catch(e){window.alert(e.message);}}}>取消</button>:null}{j.result_available&&['export_failed','interrupted','failed'].includes(j.status)?<button onClick={async()=>{try{await api('upscale/jobs/'+j.id+'/save',{});await onGPURefresh();}catch(e){window.alert(e.message);}}}>保存を再試行（再推論なし）</button>:null}<>{j.params.source_id?<button onClick={()=>onGPULoad(j)}>条件を復元・新しく実行の準備</button>:null}</><details><summary>記録</summary><pre>{JSON.stringify(j,null,2)}</pre></details></td></tr>:<tr key={j.id}>
 <td>{new Date(j.created).toLocaleString('ja-JP')}<strong className={'status '+j.status}>{j.params.provider==='qwen'&&j.status==='sending'?'ローカル処理中':names[j.status]} · {j.params.provider==='qwen'?'Qwenローカル':j.params.provider==='mock'?'モック':'実API'}</strong><small>{j.elapsed??(j.started?Math.max(0,Math.floor(Date.now()/1000-j.started)):0)}秒</small></td>
 <td><div className="truncate">{j.params.change||j.params.prompt}</div><small>{j.message}</small>{j.status==='unknown'?<p className="warning">再実行は追加課金の可能性があります。</p>:null}</td>
 <td>{j.params.model.replace('gpt-image-','')} / {j.params.provider==='qwen'?`${j.params.qwen_steps} steps · seed ${j.params.qwen_seed}`:j.params.quality}{j.params.provider==='qwen'&&j.qwen_seed_used!=null?<small>実行シード: {j.qwen_seed_used}</small>:null}<small>要求 {j.params.width} × {j.params.height}</small><small>{j.params.provider!=='openai'?'API料金なし':j.estimate!=null?'使用量からの概算: $'+j.estimate.toFixed(5):['queued','sending'].includes(j.status)?'料金集計待ち':['cancelled','failed'].includes(j.status)?'概算料金なし（取消・失敗）':'料金不明（無料とは限りません）'}</small></td>
 <td><div className="result-thumbs">{j.outputs.map((o,index)=><div className="history-output" key={o.id}><button onClick={()=>onResult(o)} aria-label={`${o.name}を拡大表示`} title={`${o.name} ${o.width}×${o.height} — クリックで拡大表示`}><img src={imageURL(o.id)} alt={o.name}/></button><small>{o.name}{j.outputs.length>1?` ${index+1}`:''}</small><button onClick={()=>onEdit(j,o)} aria-label={`${o.name}を次の編集対象にする`}>次の編集対象にする</button><a href={'/api/assets/'+o.id+'/download'} download aria-label={`${o.name}${j.outputs.length>1?` ${index+1}`:''}をPNGでダウンロード`}>PNGダウンロード</a></div>)}</div>
 <button onClick={()=>onLoad(j)}>条件を復元・新しく実行の準備</button>{j.params.provider==='qwen'&&j.status==='sending'?<button onClick={()=>onCancel(j.id)}>Qwen処理を取消</button>:null}{j.status==='queued'?<button onClick={()=>onCancel(j.id)}>待機取消</button>:null}{j.recovery&&j.status!=='sending'?<button onClick={()=>onReprocess(j.id)}>保存応答を再処理（無料・API再送なし）</button>:null}
 {j.prompt_enhancement?<details><summary>採用した指示補強（PE-T2I）</summary><p>元の指示</p><pre>{j.prompt_enhancement.source_prompt}</pre><p>補強結果</p><pre>{j.prompt_enhancement.result.rewritten_prompt}</pre><p>実際に送信した指示</p><pre>{j.params.prompt}</pre></details>:null}<details><summary>記録</summary>{j.mask?<a href={'/api/assets/'+j.mask.id+'/download'} download>{j.params.provider==='qwen'?'Qwen編集マスクPNG':'APIマスクPNG'}</a>:null}{j.recovery?<p><a href={'/api/jobs/'+j.id+'/recovery'} download>応答データを回収</a></p>:null}{j.outputs.map(o=><p key={o.id}><a href={'/api/assets/'+o.id+'/original'} download>{o.name}の原データ</a></p>)}<pre>{JSON.stringify(j,null,2)}</pre></details></td>
 </tr>)}</tbody></table></div>}</section>;
}
